// types/order-info.ts

export interface OrderInfo {
  order_number: string;
  customer_name: string;
  form_status: string;
  tgl_chat: string | null;
  tgl_acara: string | null;
  deadline: string | null;
  acara: string | null;
  kebutuhan_acara: string | null;
  kategori: string | null;
  order_via: string | null;
  order_via_channel: string | null;
  sumber_media: string | null;
  sumber_detail: string | null;
  kgj_instagram_account: string | null;
  kgj_instagram_account_custom: string | null;
  dari_artis: boolean | null;
  dari_artis_detail: string | null;
  harga: number | null;
  dp_amount: number | null;
  customer_wa: string | null;
  customer_email: string | null;
  customer_instagram: string | null;
  alamat_pengiriman: string | null;
  kelurahan: string | null;
  kecamatan: string | null;
  kabupaten_kota: string | null;
  provinsi: string | null;
  kodepos: string | null;
  alat_ukur: string | null;
  ukuran_pria: string | null;
  ukiran_pria: string | null;
  jenis_cincin_pria: string | null;
  ukuran_wanita: string | null;
  ukiran_wanita: string | null;
  jenis_cincin_wanita: string | null;
  jenis_cincin_features: string[];
  font: string | null;
  laser_position: string | null;
  pengiriman: string | null;
  box: string | null;
  transfer_ke_bank: string | null;
  current_stage: string | null;
  status: string | null;
  tgl_order: string | null;
  ukiran_cincin_pria: string | null;
  gramasi_pria: number | null;
  ukiran_cincin_wanita: string | null;
  gramasi_wanita: number | null;
  model_bentuk_pria: string[] | null;
  microsetting_pria: string[] | null;
  detail_laser_pria: string[] | null;
  detail_finishing_pria: string[] | null;
  model_bentuk_wanita: string[] | null;
  microsetting_wanita: string[] | null;
  detail_laser_wanita: string[] | null;
  detail_finishing_wanita: string[] | null;
}
