export const C = {
  page: "var(--color-parch-page)",
  card: "var(--color-parch-card)",
  header: "var(--color-parch-header)",
  raised: "var(--color-parch-raised)",
  border: "var(--color-parch-border)",
  gold: "#B89B5B",
  goldDim: "var(--color-gold-dim)",
  goldText: "var(--color-gold-text)",
  ink: "var(--color-text-ink)",
  sepia: "var(--color-text-sepia)",
  faded: "var(--color-text-faded)",
  ghost: "var(--color-text-ghost)",
  sage: "#4A7A3A",
  terra: "#9A3A20",
  amber: "#8A6010",
};

export const ROLE_DISPLAY: Record<string, string> = {
  leader_hc: "Leader HC",
  leader_operational: "Leader Operasional",
  leader_production: "Leader Produksi",
  leader_marketing: "Leader Marketing",
  leader_sales: "Leader Sales",
  leader_fat: "Leader FAT",
  leader_rnd: "Leader RND",
  leader_safar: "Leader Safar",
  leader_ga: "Leader GA",
  operational_supervisor: "Spv. Operasional",
  production_supervisor: "Spv. Produksi",
  superadmin: "Super Admin",
};
